default_language_version:
    python: python3.7
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        args:
          - --line-length=79
  - repo: https://github.com/pycqa/flake8
    rev: 3.8.1
    hooks:
    - id: flake8
      args:
        - --ignore=E203,W503
  # - repo: https://github.com/timothycrosley/isort
  #   rev: 4.3.19
  #   hooks:
  #     - id: isort
  ## Temporarily disabled since the API is disabled on the local gitlab instance
  #- repo: https://gitlab.com/devopshq/gitlab-ci-linter
  #  rev: v1.0.0
  #   hooks:
  #     - id: gitlab-ci-linter
  #       args:
  #         - --server=https://git.grammatech.com
  #         - --filename=.gitlab-ci.yml
  - repo: https://github.com/pycqa/pylint
    rev: pylint-2.6.0
    hooks:
    -  id: pylint
       args:
        - --disable=all
        - --enable=F
        - --enable=unreachable
        - --enable=duplicate-key
        - --enable=unnecessary-semicolon
        - --enable=global-variable-not-assigned
        - --enable=binary-op-exception
        - --enable=bad-format-string
        - --enable=anomalous-backslash-in-string
        - --enable=bad-open-mode
        - --enable=redefined-builtin
